// Generated by CoffeeScript 1.12.6
var JSColor, JSEscape, JSLog, JSMakeRange, JSPointMake, JSRectMake, JSSearchPathForDirectoriesInDomains, JSSizeMake, UniqueID, getApplicationFrame, getBounds, getBrowser, getCookieValue, isAndroid, isConfirm, isTouch, objCopy, objectNum, random, sprintf,
  slice = [].slice;

JSLog = function() {
  var a, b, data, i, len1;
  a = arguments[0], b = 2 <= arguments.length ? slice.call(arguments, 1) : [];
  for (i = 0, len1 = b.length; i < len1; i++) {
    data = b[i];
    a = a.replace('%@', data);
  }
  console.log(a);
  return a;
};

sprintf = function() {
  var a, b, data, data2, i, len1, match, num, repstr, zero;
  a = arguments[0], b = 2 <= arguments.length ? slice.call(arguments, 1) : [];
  for (i = 0, len1 = b.length; i < len1; i++) {
    data = b[i];
    match = a.match(/%0\d*@/);
    if ((match != null)) {
      repstr = match[0];
      num = parseInt(repstr.match(/\d+/));
      zero = "";
      while (zero.length < num) {
        zero += "0";
      }
      data2 = (zero + data).substr(-num);
      a = a.replace(repstr, data2);
    } else {
      a = a.replace('%@', data);
    }
  }
  return a;
};

isConfirm = function(str) {
  if (window.confirm(str)) {
    return 1;
  }
};

getCookieValue = function(arg) {
  var cookieData, endPoint, startPoint1, startPoint2;
  if (arg) {
    cookieData = document.cookie + ";";
    startPoint1 = cookieData.indexOf(arg);
    startPoint2 = cookieData.indexOf("=", startPoint1) + 1;
    endPoint = cookieData.indexOf(";", startPoint1);
    if (startPoint2 < endPoint && startPoint1 > -1) {
      cookieData = cookieData.substring(startPoint2, endPoint);
      cookieData = cookieData;
      return cookieData;
    }
  }
  return false;
};

UniqueID = function() {
  var S4;
  S4 = function() {
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  };
  return S4() + S4() + "-" + S4() + "-" + S4() + "-" + S4() + "-" + S4() + S4() + S4();
};

JSRectMake = function(x, y, w, h) {
  var frame;
  frame = new JSRect();
  frame.origin.x = x;
  frame.origin.y = y;
  frame.size.width = w;
  frame.size.height = h;
  return frame;
};

JSPointMake = function(x, y) {
  var point;
  point = new JSPoint();
  point.x = x;
  point.y = y;
  return point;
};

JSSizeMake = function(w, h) {
  var size;
  size = new JSSize();
  size.width = w;
  size.height = h;
  return size;
};

JSMakeRange = function(loc, len) {
  var range;
  range = new JSRange();
  range.location = loc;
  range.length = len;
  return range;
};

getApplicationFrame = function() {
  var frame;
  frame = JSRectMake(0, 0, window.innerWidth - 1, window.innerHeight - 1);
  return frame;
};

getBounds = function() {
  var frame, height, width;
  width = document.documentElement.clientWidth - 2;
  height = document.documentElement.clientHeight - 2;
  frame = JSRectMake(0, 0, width, height);
  return frame;
};

JSColor = function(color) {
  var ret;
  ret = color;
  switch (color) {
    case "clearColor":
      ret = "transparent";
  }
  return ret;
};

JSSearchPathForDirectoriesInDomains = function(kind) {
  var ret;
  ret = "";
  switch (kind) {
    case "JSLibraryDirectory":
      ret = "Library";
      break;
    case "JSDocumentDirectory":
      ret = "Documents";
      break;
    case "JSPictureDirectory":
      ret = "Media/Picture";
      break;
    case "JSSystemDirectory":
      ret = "syslibs";
      break;
    case "JSBackendDirectory":
      ret = "backend";
  }
  return ret;
};

random = function(max) {
  return Math.floor(Math.random() * (max + 1));
};

JSEscape = function(str) {
  if ((str != null)) {
    str = str.replace(/&/g, "&amp;");
    str = str.replace(/\'/g, "&quot;");
    str = str.replace(/\"/g, "&quot;");
    str = str.replace(/</g, "&lt;");
    str = str.replace(/>/g, "&gt;");
  }
  return str;
};

objectNum = function(obj) {
  if ((obj != null)) {
    return Object.keys(obj).length;
  } else {
    return 0;
  }
};

isTouch = function() {
  return 'ontouchstart' in window;
};

isAndroid = function() {
  return navigator.userAgent.indexOf('Android') !== -1;
};

getBrowser = function() {
  var browser, kind, ua;
  ua = navigator.userAgent;
  if (ua.match(".*iPhone.*")) {
    kind = 'iOS';
  } else if (ua.match(".*Android")) {
    kind = 'Android';
  } else if (ua.match(".*Windows.*")) {
    kind = 'Windows';
  } else if (ua.match(".*BlackBerry.*")) {
    kind = 'BlackBerry';
  } else if (ua.match(".*Symbian.*")) {
    kind = 'Symbian';
  } else if (ua.match(".*Macintosh.*")) {
    kind = 'Mac';
  } else if (ua.match(".*Linux.*")) {
    kind = 'Linux';
  } else {
    kind = 'Unknown';
  }
  if (ua.match(".*Safari.*") && !ua.match(".*Android.*") && !ua.match(".*Chrome.*")) {
    browser = 'Safari';
  } else if (ua.match(".*Gecko.*Firefox.*")) {
    browser = "Firefox";
  } else if (ua.match(".*Opera*")) {
    browser = "Opera";
  } else if (ua.match(".*MSIE*")) {
    browser = "MSIE";
  } else if (ua.match(".*Gecko.*Chrome.*")) {
    browser = "Chrome";
  } else {
    browser = 'Unknown';
  }
  return {
    'kind': kind,
    'browser': browser
  };
};

objCopy = function(a) {
  return $.extend(true, {}, a);
};

//# sourceMappingURL=library.js.map
